@url = https://animated-funicular-jjj5qx564qxj2pxxp-3000.app.github.dev/

GET {{url}}/api/v1/generos

###
POST {{url}}/api/v1/generos
Content-Type: application/json

{
    "id" : 10,
    "nome" : "Biografia"
}